version: "2"

services:

  pi-hole:
    network_mode: bridge
    container_name: pihole
    restart: always
    build:
      context: docker-files/pi-hole
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=pihole.local
      - ServerIP=192.168.0.119

    ports:
      - 8080:80
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - /etc/pihole/
      - ./etc/pihole/lan.list:/etc/pihole/lan.list
    extra_hosts:
      - "pihole.local:192.168.0.119"

  nginx-proxy:
    network_mode: bridge
    container_name: nginx-proxy
    restart: always
    build:
      context: docker-files/nginx-proxy
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"

    expose:
      - "80"

  desktop:
    network_mode: bridge
    container_name: desktop
    restart: always
    build:
      context: docker-files/docker-vnc
      dockerfile: Dockerfile.ubuntu.icewm.vnc
    ports:
      - "5901:5901"
      - "6901:6901"

  timemachine:
    network_mode: bridge
    container_name: timemachine
    restart: always
    build:
      context: docker-files/timemachine
      dockerfile: Dockerfile
    ports:
      - "548:548"
      - "636:636"


  php:
    network_mode: bridge
    container_name: php
    image: "php:7-apache"
    environment:
      - UID=$UID
      - GID=$GID
      - VIRTUAL_HOST=php.local
    volumes:
      - "/var/www/html:/var/www/html"
      - "./scripts/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint"

  plex:
    network_mode: bridge
    container_name: plex
    image: "linuxserver/plex"
    volumes:
      - "/tank/media/x-rated:/data/movies/xrated"
      - "/tank/media/tv-shows:/data/tvshows"
      - "/tank/media/transcode:/transcode"
      - "/tank/media/plex-config:/config"
      - "/tank/media/movies:/data/movies/movies"
    ports:
      - 1900:1900/udp
      - 32400:32400/tcp
      - 32400:32400/udp
      - 32469:32469/tcp
      - 32469:32469/udp
        #  - 5353:5353/udp
    environment:
      - PGID=$GID
      - UID=$UID
    
  torrent:
    image: haugene/transmission-openvpn
    container_name: torrent1
    privileged: true
    restart: always
    ports:
      - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /tank/media:/media_host:rw
      - /tank/downloads:/data:rw
      - /etc/localtime:/etc/localtime:ro
        #      - /your/storage/path/:/data
    environment:
      - VIRTUAL_HOST=torrent.local
      - OPENVPN_PROVIDER=PUREVPN
      - OPENVPN_CONFIG=Netherlands1-tcp
      - PUID=$UID
      - PGID=$GID
      - OPENVPN_USERNAME=username
      - OPENVPN_PASSWORD=password
      - OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_ALT_SPEED_DOWN=50
      - TRANSMISSION_ALT_SPEED_ENABLED=false
      - TRANSMISSION_ALT_SPEED_TIME_BEGIN=540
      - TRANSMISSION_ALT_SPEED_TIME_DAY=127
      - TRANSMISSION_ALT_SPEED_TIME_ENABLED=false
      - TRANSMISSION_ALT_SPEED_TIME_END=1020
      - TRANSMISSION_ALT_SPEED_UP=50
      - TRANSMISSION_BIND_ADDRESS_IPV4=0.0.0.0
      - TRANSMISSION_BLOCKLIST_ENABLED=false
      - TRANSMISSION_BLOCKLIST_URL=http://www.example.com/blocklist
      - TRANSMISSION_CACHE_SIZE_MB=4
      - TRANSMISSION_DHT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/completed
      - TRANSMISSION_DOWNLOAD_LIMIT=100
      - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5
      - TRANSMISSION_ENCRYPTION=1
      - TRANSMISSION_IDLE_SEEDING_LIMIT=30
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_LPD_ENABLED=false
      - TRANSMISSION_MAX_PEERS_GLOBAL=200
      - TRANSMISSION_MESSAGE_LEVEL=2
      - TRANSMISSION_PEER_CONGESTION_ALGORITHM=
      - TRANSMISSION_PEER_ID_TTL_HOURS=6
      - TRANSMISSION_PEER_LIMIT_GLOBAL=200
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=50
      - TRANSMISSION_PEER_PORT=51413
      - TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535
      - TRANSMISSION_PEER_PORT_RANDOM_LOW=49152
      - TRANSMISSION_PEER_PORT_RANDOM_ON_START=false
      - TRANSMISSION_PEER_SOCKET_TOS=default
      - TRANSMISSION_PEX_ENABLED=true
      - TRANSMISSION_PORT_FORWARDING_ENABLED=false
      - TRANSMISSION_PREALLOCATION=1
      - TRANSMISSION_PREFETCH_ENABLED=1
      - TRANSMISSION_QUEUE_STALLED_ENABLED=true
      - TRANSMISSION_QUEUE_STALLED_MINUTES=30
      - TRANSMISSION_RATIO_LIMIT=2
      - TRANSMISSION_RATIO_LIMIT_ENABLED=false
      - TRANSMISSION_RENAME_PARTIAL_FILES=true
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RPC_PASSWORD=password
      - TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_RPC_URL=/transmission/
      - TRANSMISSION_RPC_USERNAME=username
      - TRANSMISSION_RPC_WHITELIST=127.0.0.1
      - TRANSMISSION_RPC_WHITELIST_ENABLED=false
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=
      - TRANSMISSION_SEED_QUEUE_ENABLED=false
      - TRANSMISSION_SEED_QUEUE_SIZE=10
      - TRANSMISSION_SPEED_LIMIT_DOWN=100
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false
      - TRANSMISSION_SPEED_LIMIT_UP=100
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false
      - TRANSMISSION_START_ADDED_TORRENTS=true
      - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_UPLOAD_LIMIT=100
      - TRANSMISSION_UPLOAD_LIMIT_ENABLED=0
      - TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=14
      - TRANSMISSION_UTP_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/data/watch
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_HOME=/data/transmission-home
