version: "2"

services:

  pi-hole:
    network_mode: bridge
    container_name: pihole
    restart: unless-stopped
    build:
      context: docker-files/pi-hole
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=pihole.local
      - ServerIP=192.168.0.119

    ports:
      - 8090:80
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - /etc/pihole/
      - ./etc/pihole/lan.list:/etc/pihole/lan.list
    extra_hosts:
      - "pihole.local:192.168.0.119"

  nginx-proxy:
    network_mode: bridge
    container_name: nginx-proxy
    restart: unless-stopped
    build:
      context: docker-files/nginx-proxy
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"

    expose:
      - "80"

  desktop:
    network_mode: bridge
    container_name: desktop
    restart: unless-stopped
    build:
      context: docker-files/docker-vnc
      dockerfile: Dockerfile.ubuntu.icewm.vnc
    ports:
      - "5901:5901"
      - "6901:6901"

  timemachine:
    network_mode: bridge
    container_name: timemachine
    restart: unless-stopped
    build:
      context: docker-files/timemachine
      dockerfile: Dockerfile
    ports:
      - "548:548"
      - "636:636"


  php:
    network_mode: bridge
    container_name: php
    image: "php:7-apache"
    environment:
      - UID=$UID
      - GID=$GID
      - VIRTUAL_HOST=php.local
    volumes:
      - "/var/www/html:/var/www/html"
      - "./scripts/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint"

  plex:
    network_mode: bridge
    container_name: plex
    restart: unless-stopped
    image: "linuxserver/plex"
    volumes:
      - "/tank/media/x-rated:/data/movies/xrated"
      - "/tank/media/tv-shows:/data/tvshows"
      - "/tank/media/transcode:/transcode"
      - "/tank/media/plex-config:/config"
      - "/tank/media/movies:/data/movies/movies"
    ports:
      - 1900:1900/udp
      - 32400:32400/tcp
      - 32400:32400/udp
      - 32469:32469/tcp
      - 32469:32469/udp
        #  - 5353:5353/udp
    environment:
      - PGID=$GID
      - UID=$UID
      - VIRTUAL_HOST=plex.local
    
  torrent:
    image: haugene/transmission-openvpn
    container_name: torrent1
    privileged: true
    restart: unless-stopped
    ports:
      - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /tank/media:/media_host:rw
      - /tank/downloads:/data:rw
      - /etc/localtime:/etc/localtime:ro
        #      - /your/storage/path/:/data
    environment:
      - VIRTUAL_HOST=torrent.local
      - OPENVPN_PROVIDER=PUREVPN
      - OPENVPN_CONFIG=Netherlands1-tcp
      - PUID=$UID
      - PGID=$GID
      - OPENVPN_USERNAME=username
      - OPENVPN_PASSWORD=password
      - OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60

  couchpotato:
    image: "linuxserver/couchpotato"
    container_name: couchpotato
    restart: unless-stopped
    ports:
      - 5050:5050
    environment:
      - TZ=$TZ
      - PGID=$GID
      - PUID=$UID
      - VIRTUAL_HOST=couchpotato.local
    volumes:
      - "/tank/media/couchpotato-config:/config"
      - "/tank/downloads/completed:/downloads"
      - "/tank/media/movies:/movies"
      - "/tank/media/sabnzb-config/nzb:/nzb"

  sabnzb:
    image: "linuxserver/sabnzbd"
    container_name: sabnzb
    restart: unless-stopped
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - TZ=$TZ
      - PGID=$GID
      - PUID=$UID
      - VIRTUAL_HOST=sabnzb.local
    volumes:
      - "/tank/media/sabnzb-config:/config"
      - "/tank/downloads/completed:/downloads"
      - "/tank/downloads/incomplete:/incomplete-downloads"



  mysql:
    image: "mariadb:10.3"
    container_name: mysql
    restart: unless-stopped
    volumes:
      - "/tank/database/mysql/:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw

  spotweb:
    image: "jgeusebroek/spotweb"
    container_name: spotweb
    volumes:
      - "/tank/media/spotnet-config:/config"
    ports:
      - 9080:80
    environment:
      - TZ=$TZ
      - SPOTWEB_DB_TYPE=pdo_mysql
      - SPOTWEB_DB_HOST=mysql
      - SPOTWEB_DB_NAME=spotweb
      - SPOTWEB_DB_USER=root
      - SPOTWEB_DB_PASS=my-secret-pw
      - VIRTUAL_HOST=spotweb.local

  sickbeard:
    image: "sickbeard/sickbeard"
    container_name: sickbeard
    volumes:
      - "/tank/downloads/torrent-files:/watch-dir:rw"
      - "/tank/downloads/completed:/downloads:rw"
      - "/tank/media/sickbeard:/datadir:rw"
      - "/tank/media:/media:rw"
    environment:
      - SICKBEARD_UID=$UID
      - SICKBEARD_GID=$GID
      - VIRTUAL_HOST=sickbeard.local
    ports:
      - 8081:8081

