version: "2"

services:

  pi-hole:
    network_mode: bridge
    container_name: pihole
    restart: always
    build:
      context: docker-files/pi-hole
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=pihole.local
      - ServerIP=192.168.0.119

    ports:
      - 8080:80
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - /etc/pihole/
      - ./etc/pihole/lan.list:/etc/pihole/lan.list
    extra_hosts:
      - "pihole.local:192.168.0.119"

  nginx-proxy:
    network_mode: bridge
    container_name: nginx-proxy
    restart: always
    build:
      context: docker-files/nginx-proxy
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"

    expose:
      - "80"

  desktop:
    network_mode: bridge
    container_name: desktop
    restart: always
    build:
      context: docker-files/docker-vnc
      dockerfile: Dockerfile.ubuntu.icewm.vnc
    ports:
      - "5901:5901"
      - "6901:6901"

  timemachine:
    network_mode: bridge
    container_name: timemachine
    restart: always
    build:
      context: docker-files/timemachine
      dockerfile: Dockerfile
    ports:
      - "548:548"
      - "636:636"
