version: "2"

services:

  pihole:
      #    network_mode: host
    networks:
      - default
    container_name: pihole
    restart: unless-stopped
    build:
      context: docker-files/pi-hole
      dockerfile: Dockerfile
    environment:
      - ServerIP=$IP_ADDRESS
      - VIRTUAL_HOST=pihole.local
      - VIRTUAL_PORT=80
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    ports:
      - 8090:80
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - /etc/pihole/
      - ./etc/pihole/resolv.conf:/etc/resolv.conf:ro
      - ./etc/pihole/lan.list:/etc/pihole/lan.list
    depends_on: ["nginx"]

#  nginx:
#    network_mode: host
#    container_name: nginx
#    restart: unless-stopped
#    build:
#      context: docker-files/nginx
#      dockerfile: Dockerfile
#    volumes:
#      - ./etc/nginx/sites-enabled:/etc/nginx/sites-enabled
#      - ./etc/nginx/conf.d:/etc/nginx/conf.d
#      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./etc/nginx/data:/www/data
#    ports:
#      - "80:80"
#      - "443:443"
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  timemachine:
    container_name: timemachine
    restart: unless-stopped
    build:
      context: docker-files/timemachine
      dockerfile: Dockerfile
    ports:
      - "548:548"
      - "636:636"
    depends_on: ["nginx"]

  php:
    container_name: php
    image: "php:7-apache"
    environment:
      - UID=$UID
      - GID=$GID
      - VIRTUAL_HOST=php.local
      - VIRTUAL_PORT=80
    volumes:
      - "/var/www/html:/var/www/html"
      - "./etc/php/entrypoint.sh:/usr/local/bin/docker-php-entrypoint"
    ports:
      - 9092:80
    networks:
      - default
    depends_on: ["nginx"]

  plex:
      #    network_mode: host
    networks:
      - default
    container_name: plex
    restart: unless-stopped
    image: "linuxserver/plex"
    volumes:
      - "/tank/media/x-rated:/data/movies/xrated"
      - "/tank/media/tv-shows:/data/tvshows"
      - "/tank/media/transcode:/transcode"
      - "/tank/media/plex-config:/config"
      - "/tank/media/movies:/data/movies/movies"
    ports:
      - 1900:1900/udp
      - 32400:32400/tcp
      - 32400:32400/udp
      - 32469:32469/tcp
      - 32469:32469/udp
      - 5353:5353/udp
    environment:
      - PGID=$GID
      - PUID=$UID
      - VERSION=latest
      - VIRTUAL_HOST=plex.local
      - VIRTUAL_PORT=32400
    depends_on: ["nginx"]

  transmission:
    image: haugene/transmission-openvpn:dev
    privileged: true
    restart: unless-stopped
    networks:
      - default
    ports:
      - "9091:9091"
    dns:
      - 1.1.1.1 
      - 1.0.0.1
    volumes:
     - /tank:/tank:rw
#     - /tank/downloads:/data:rw
     - /etc/localtime:/etc/localtime:ro
     - ./etc/transmission/resolv.conf:/etc/resolv.conf:ro
#       #      - /your/storage/path/:/data
     - ./etc/vpn/purevpn:/etc/openvpn/purevpn
    environment:
      - VIRTUAL_HOST=transmission.local
      - VIRTUAL_PORT=9091
      - OPENVPN_PROVIDER=PUREVPN
      - OPENVPN_CONFIG=Belgium-tcp
      - PUID=$UID
      - PGID=$GID
      - OPENVPN_USERNAME=$OPENVPN_USERNAME
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        #entrypoint: ["cd", "/etc/openvpn",";",  "./adjustConfigs.sh", "purevpn"]
    depends_on: ["nginx"]

  couchpotato:
    image: "linuxserver/couchpotato"
    container_name: couchpotato
    restart: unless-stopped
    ports:
      - 5050:5050
    networks:
      - default
    environment:
      - TZ=$TZ
      - PGID=$GID
      - PUID=$UID
      - VIRTUAL_PORT=5050
      - VIRTUAL_HOST=couchpotato.local
    volumes:
      - "/tank/media/couchpotato-config:/config"
        #- "/tank/downloads/completed:/downloads"
        #- "/tank/media/movies:/movies"
        #- "/tank/media/sabnzb-config/nzb:/nzb"
      - /tank:/tank
    depends_on: ["nginx"]

  sabnzb:
    image: "linuxserver/sabnzbd"
    container_name: sabnzb
    restart: unless-stopped
    ports:
      - 8080:8080
      - 9090:9090
    networks:
      - default
    environment:
      - TZ=$TZ
      - PGID=$GID
      - PUID=$UID
      - VIRTUAL_HOST=sabnzb.local
      - VIRTUAL_PORT=8080
    volumes:
      - "/tank/media/sabnzb-config:/config"
        #- "/tank/downloads/completed:/downloads"
        #- "/tank/downloads/incomplete:/incomplete-downloads"
        #- "/tank/media:/all-media"
      - /tank:/tank
    depends_on: ["nginx"]


  mysql:
    image: "mariadb:10.3"
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - "/tank/database/mysql/:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    depends_on: ["nginx"]

  spotweb:
    build:
      context: "./docker-files/spotweb"
      dockerfile: Dockerfile
    container_name: spotweb
    volumes:
      - "/tank/media/spotnet-config:/config"
      - "./docker-files/spotweb/entrypoint.sh:/entrypoint.sh"
      - "./docker-files/spotweb/files/hosts.conf:/etc/apache2/sites-enabled/000-default.conf"
    ports:
      - 9080:80
    networks:
      - default
    environment:
      - TZ=$TZ
      - SPOTWEB_DB_TYPE=pdo_mysql
      - SPOTWEB_DB_HOST=mysql
      - SPOTWEB_DB_NAME=spotweb
      - SPOTWEB_DB_USER=root
      - SPOTWEB_DB_PASS=my-secret-pw
        #      - VIRTUAL_HOST=spotweb.local
        #      - VIRTUAL_HOST=80
    depends_on: ["nginx"]


  sickbeard:
      #image: "sickbeard/sickbeard"
    image: "linuxserver/sickbeard"
    container_name: sickbeard
    volumes:
      - "/tank/downloads/torrent-files:/watch-dir:rw"
      - "/tank/downloads/completed:/downloads:rw"
      - "/tank/media/sickbeard:/config:rw"
      - "/tank/media:/media:rw"
    environment:
      - PUID=$UID
      - PGID=$GID
      - VIRTUAL_HOST=sickbeard.local
      - VIRTUAL_PORT=8081
    ports:
      - 8081:8081
    networks:
      - default
    depends_on: ["nginx"]


  selfoss:
    build:
        context: docker-files/selfoss
        dockerfile: Dockerfile
    container_name: selfoss
    volumes:
      - "/tank/media/selfoss:/var/www/html/data"
      - "./etc/selfoss/entrypoint.sh:/usr/local/bin/docker-php-entrypoint"
    environment:
      - UID=$UID
      - GID=$GID
      - VIRTUAL_HOST=selfoss.local
      - VIRTUAL_PORT=80
        #    ports:
        #      - 8083:80
    networks:
      - default
    depends_on: ["nginx"]


networks:
  default:
    driver: bridge
